apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scoring
  template:
    metadata:
      labels:
        app: scoring
    spec:
      containers:
        - name: app
          image: morozco/laurel-scoring
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/Laurel
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: scoring
spec:
  selector:
    app: scoring
  ports:
    - port: 8083
      targetPort: 8080
  type: LoadBalancer